// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9ASPVpOGglW9ZhGvFf4mZKDtGdlo6Gk4',
    appId: '1:263129868837:web:868f2dc3d041ae2a82edcc',
    messagingSenderId: '263129868837',
    projectId: 'choose-songs',
    authDomain: 'choose-songs.firebaseapp.com',
    storageBucket: 'choose-songs.firebasestorage.app',
    measurementId: 'G-HPQ0WQEYPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDWlfvBjVQRcAThAhVZDwVxnZjqjVOZfA',
    appId: '1:263129868837:android:21af547d9d8a56e682edcc',
    messagingSenderId: '263129868837',
    projectId: 'choose-songs',
    storageBucket: 'choose-songs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu7yPxhR6rrsnWQvMGbMOY5V887RWP_T0',
    appId: '1:263129868837:ios:6690f29de88d362c82edcc',
    messagingSenderId: '263129868837',
    projectId: 'choose-songs',
    storageBucket: 'choose-songs.firebasestorage.app',
    iosBundleId: 'com.example.chooseSongs',
  );
}
